apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: developers-gitops
spec:
  destination:
    namespace: demo-dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/OskarMarthinussen/helm-chart.git'
    path: dev/app1
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: demo
