apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app1-dev
  namespace: gitops-developers
spec:
  destination:
    namespace: demo-dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/OskarMarthinussen/testing-ok.git'
    path: dev/app1
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: demo
