apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oskar-dev-private-repo-app1
  namespace: gitops-developers
spec:
  destination:
    namespace: poseidon2-dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/TeamPoseidonOCP/poseidon1_private_repo.git'
    path: poseidon2/applications
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: poseidon2
