apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-preprod
  namespace: demo-preprod
spec:
  destination:
    namespace: demo-preprod
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/OskarMarthinussen/helm-chart.git'
    path: preprod/app1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  project: demo
